# Generated by Django 5.1.5 on 2025-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lecture_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
    ]
