# Generated by Django 5.1.5 on 2025-04-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contactinfo_contactrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='ContactRequest',
        ),
    ]
