# Generated by Django 5.1.5 on 2025-04-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_contactrequest_created_at'),
        ('userprofile', '0010_alter_school_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contact', to='userprofile.location', verbose_name='Местоположение'),
        ),
    ]
