# Generated by Django 5.1.5 on 2025-05-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contact_location'),
        ('userprofile', '0010_alter_school_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prog',
            name='school_class',
            field=models.ManyToManyField(blank=True, related_name='программа', to='userprofile.schoolclass', verbose_name='Учебные классы'),
        ),
    ]
