# Generated by Django 5.1.5 on 2025-05-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_prog_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='prog',
            name='total_places',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего мест'),
        ),
    ]
