# Generated by Django 5.1.5 on 2025-02-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['email'], 'verbose_name': 'Подписчика', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
