# Generated by Django 5.1.5 on 2025-02-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_subscriber_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
