# Generated by Django 5.1.5 on 2025-03-09 17:48

import django.db.models.deletion
import django_admin_geomap
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.RemoveField(
            model_name='school',
            name='school',
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='school',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вебсайт'),
        ),
        migrations.AddField(
            model_name='school',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school', to='userprofile.location', verbose_name='Местоположение'),
        ),
    ]
