# Generated by Django 5.1.5 on 2025-03-09 18:40

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_location_remove_school_school_school_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
