# Generated by Django 5.1.5 on 2025-04-15 09:56

import main.fields
import userprofile.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=main.fields.WEBPField(blank=True, null=True, upload_to=userprofile.models.image_folder, verbose_name='Фото'),
        ),
    ]
