# Generated by Django 5.1.5 on 2025-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('U', 'не выбран'), ('M', 'мужской'), ('F', 'женский')], default='U', max_length=1, verbose_name='Пол'),
        ),
    ]
