# Generated by Django 5.1.5 on 2025-04-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='site',
        ),
    ]
