# Generated by Django 5.1.5 on 2025-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_alter_school_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='grade',
            field=models.PositiveIntegerField(default=1, verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
